### ISSUE TITLE
Clean Timeseries and Simulations Plots

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#293]
The time series and simulations plots need to be cleaned up.

* Titles are sometimes very long and extend beyond the plot window

* Menu for different plot types is missing

* legend is strangely large.  It also might look better if there was some space between the legend and the plot.

* implement with seaborn?

**Comment by farrieta9** [comment]
* Make the this viewer the same style as the wofviewer
* Make the wofviewer into a time series viewer. All time series would use this view

**Comment by farrieta9** [comment]
What if we got rid of the context view for the database.  My reason for this would be because add, and export are going to be part of the time series viewer.  This would help clean up the code in the project.  Its just an idea

**Comment by ryanzj725** [comment]
I'm with you on it. -Ryan

On Nov 21, 2015 10:17 AM, Francisco Arrieta <notifications@github.com> wrote:

What if we got rid of the context view for the database. My reason for this would be because add, and export are going to be part of the time series viewer. This would help clean up the code in the project. Its just an idea

-
